name = "Decoration Perfomance"
author = "Lostopkk"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5024d99b0508f6d58589e84e9c9cacc6d361e3c60e7052bcad86be2c3b777a81"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
