name = "Decoration Perfomance"
author = "Lostopkk"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98427c5e04a0b42a9df404e74c0ee42e839983fa488ac9620cfef9d8f060a3c0"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
