
[laptopSettings]
	#The amount of ticks the laptop waits until sending another ping to it's connected router.
	#Range: 1 ~ 200
	pingRate = 20

[routerSettings]
	#The maximum amount of devices that can be connected to the router.
	#Range: 1 ~ 64
	maxDevices = 16
	#The amount of ticks the router waits before sending out a beacon signal. Higher number will increase performance but devices won't know as quick if they lost connection.
	#Range: 1 ~ 200
	beaconInterval = 20
	#The range that routers can produce a signal to devices. This is the radius in blocks. Be careful when increasing this value, the performance is O(n^3) and larger numbers will have a bigger impact on the server
	#Range: 10 ~ 100
	signalRange = 20

[printerSettings]
	#The maximum amount of paper that can be used in the printer.
	#Range: 0 ~ 99
	maxPaperCount = 64
	#If enable, overrides all printing times with customPrintSpeed property
	overridePrintSpeed = false
	#The amount of seconds it takes to print a page. This is overridden if overridePrintSpeed is enabled.
	#Range: 1 ~ 600
	customPrintSpeed = 20

[pixelPainter]
	#Should the pixels on printed pictures be render in 3D? Warning, this will decrease the performance of the game. You shouldn't enable it if you have a slow computer.
	renderPrintedIn3d = false
	#Enable or disable the Pixel Painter app.
	enabled = true

[debug]
	#Display a button to access a worldless laptop
	debugButton = false

