enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingDepth = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
adorn = false
everycomp = true
mcwfences = true
farmersdelight = true
minekea = true
mcwroofs = true
infinitybuttons = true
campanion = true
overweight_farming = true
mcwwindows = true
croptopia = true
brewery = true
immersive_portals = true
redstonepen = true
cozy = true
another_furniture = true
statues = true
automobility = true
dramaticdoors = true
coxinhautilities = true
comforts = true
bitsandchisels = true
mcwpaths = true
campchair = true
mcwlights = true
mcwbridges = true
milk = true
marketcrates = true
mcwtrpdoors = true
botanypots = true
devices = true
chisel = true
sandwichable = true
modern_industrialization = true
charm = true
treechop = true
mca = true
naturalist = true
mcwdoors = true
supplementaries = true
dishes = true
iammusicplayer = true
create = true
seasons = true
extended_drawers = true
mishanguc = true
minecraft = true
transportables = true
immersive_weathering = true
decorative_blocks = true
computercraft = true
xercamusic = true
vinery = true
kibe = true
ad_astra = true
blockus = true
